---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - export PROJECTPATH=$HOME/whatsapp-clone
    - mkdir -p $PROJECTPATH
    - /bin/cp -R app $PROJECTPATH/
    - /bin/cp -R bootstrap $PROJECTPATH/
    - /bin/cp -R config $PROJECTPATH/
    - /bin/cp -R database $PROJECTPATH/
    - /bin/cp -R resources $PROJECTPATH/
    - /bin/cp -R routes $PROJECTPATH/
    - /bin/cp -R tests $PROJECTPATH/
    - /bin/cp artisan $PROJECTPATH/
    - /bin/cp composer.json $PROJECTPATH/
    - /bin/cp composer.lock $PROJECTPATH/
    - /bin/cp package.json $PROJECTPATH/
    - /bin/cp package-lock.json $PROJECTPATH/
    - /bin/cp vite.config.ts $PROJECTPATH/
    - /bin/cp tsconfig.json $PROJECTPATH/
    - /bin/cp tailwind.config.js $PROJECTPATH/
    - /bin/cp -R public/* $DEPLOYPATH/
    - /bin/cp public/.htaccess $DEPLOYPATH/
    - cd $PROJECTPATH
    - test -f .env || cp .env.example .env
    - sed -i 's/DB_CONNECTION=msyql/DB_CONNECTION=mysql/g' .env
    - sed -i 's/DB_CONNECTION=msql/DB_CONNECTION=mysql/g' .env
    - grep -q "APP_KEY=" .env || php artisan key:generate --force
    # Apply provided environment configuration
    - cat > .env.cpanel << 'ENVCPANEL'
APP_NAME="ss"
APP_ENV=local
APP_KEY=base64:1p9xH6s+dK5rbcwzq8ft8ak3zA7mGpJyey42iRpOIgY=
APP_DEBUG=true
APP_URL=http://patient-purple-iguana.72-61-166-241.cpanel.site
APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US
APP_MAINTENANCE_DRIVER=file
PHP_CLI_SERVER_WORKERS=4
BCRYPT_ROUNDS=12
LOG_CHANNEL=stack
LOG_STACK=single
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=debug
DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=chaat2h2jjj_we3w4fd
DB_USERNAME=chaat2h2jjj_faaaaw34tga4
DB_PASSWORD="&J3!H{q-?JcG[,8w"
SESSION_DRIVER=database
SESSION_LIFETIME=120
SESSION_ENCRYPT=false
SESSION_PATH=/
SESSION_DOMAIN=null
BROADCAST_CONNECTION=reverb
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
CACHE_STORE=database
MEMCACHED_HOST=127.0.0.1
REDIS_CLIENT=phpredis
REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379
MAIL_MAILER=log
MAIL_SCHEME=null
MAIL_HOST=127.0.0.1
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_FROM_ADDRESS="hello@example.com"
MAIL_FROM_NAME="${APP_NAME}"
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false
VITE_APP_NAME="${APP_NAME}"
REVERB_APP_ID=
REVERB_APP_KEY=
REVERB_APP_SECRET=
REVERB_HOST="72.61.166.241"
REVERB_PORT=8080
REVERB_SCHEME=http
VITE_REVERB_APP_KEY="${REVERB_APP_KEY}"
VITE_REVERB_HOST="${REVERB_HOST}"
VITE_REVERB_PORT="${REVERB_PORT}"
VITE_REVERB_SCHEME="${REVERB_SCHEME}"
ENVCPANEL
    - for K in APP_NAME APP_ENV APP_KEY APP_DEBUG APP_URL APP_LOCALE APP_FALLBACK_LOCALE APP_FAKER_LOCALE APP_MAINTENANCE_DRIVER PHP_CLI_SERVER_WORKERS BCRYPT_ROUNDS LOG_CHANNEL LOG_STACK LOG_DEPRECATIONS_CHANNEL LOG_LEVEL DB_CONNECTION DB_HOST DB_PORT DB_DATABASE DB_USERNAME DB_PASSWORD SESSION_DRIVER SESSION_LIFETIME SESSION_ENCRYPT SESSION_PATH SESSION_DOMAIN BROADCAST_CONNECTION FILESYSTEM_DISK QUEUE_CONNECTION CACHE_STORE MEMCACHED_HOST REDIS_CLIENT REDIS_HOST REDIS_PASSWORD REDIS_PORT MAIL_MAILER MAIL_SCHEME MAIL_HOST MAIL_PORT MAIL_USERNAME MAIL_PASSWORD MAIL_FROM_ADDRESS MAIL_FROM_NAME AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION AWS_BUCKET AWS_USE_PATH_STYLE_ENDPOINT VITE_APP_NAME REVERB_APP_ID REVERB_APP_KEY REVERB_APP_SECRET REVERB_HOST REVERB_PORT REVERB_SCHEME VITE_REVERB_APP_KEY VITE_REVERB_HOST VITE_REVERB_PORT VITE_REVERB_SCHEME; do sed -i \"/^$K=/d\" .env; done
    - cat .env.cpanel >> .env
    - sed -i '/^VITE_ENABLE_ECHO=/d' .env
    - echo "VITE_ENABLE_ECHO=true" >> .env
    # Ensure Reverb keys exist if left empty
    - php -r '$p=\".env\";$s=file_get_contents($p);$set=function($k,$v)use(&$s){$s=preg_replace(\"/^{$k}=.*$/m\",\"{$k}={$v}\",$s,1,$c);if(!$c)$s.=\"\\n{$k}={$v}\\n\";};if(preg_match(\"/^REVERB_APP_ID=\\s*$/m\",$s)){$set(\"REVERB_APP_ID\",bin2hex(random_bytes(16)));}if(preg_match(\"/^REVERB_APP_KEY=\\s*$/m\",$s)){$v=bin2hex(random_bytes(16));$set(\"REVERB_APP_KEY\",$v);$set(\"VITE_REVERB_APP_KEY\",$v);}if(preg_match(\"/^REVERB_APP_SECRET=\\s*$/m\",$s)){$set(\"REVERB_APP_SECRET\",bin2hex(random_bytes(32)));}file_put_contents($p,$s);'
    - sed -i '/^VITE_ENABLE_ECHO=/d' .env
    - echo "VITE_ENABLE_ECHO=false" >> .env
    - composer install --optimize-autoloader --no-dev --no-interaction
    - npm install --production
    - rm -rf $DEPLOYPATH/build
    - npm run build
    - /bin/cp -R public/build $DEPLOYPATH/
    - cd $DEPLOYPATH
    - rm -f storage
    - ln -s $PROJECTPATH/storage/app/public storage
    - cd $PROJECTPATH
    - chmod -R 775 storage
    - chmod -R 775 bootstrap/cache
    - php artisan migrate --force
    - php artisan db:seed --class=UserSeeder --force
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
