---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - export PROJECTPATH=$HOME/whatsapp-clone
    - mkdir -p $PROJECTPATH
    - /bin/cp -R app $PROJECTPATH/
    - /bin/cp -R bootstrap $PROJECTPATH/
    - /bin/cp -R config $PROJECTPATH/
    - /bin/cp -R database $PROJECTPATH/
    - /bin/cp -R resources $PROJECTPATH/
    - /bin/cp -R routes $PROJECTPATH/
    - /bin/cp -R tests $PROJECTPATH/
    - /bin/cp artisan $PROJECTPATH/
    - /bin/cp composer.json $PROJECTPATH/
    - /bin/cp composer.lock $PROJECTPATH/
    - /bin/cp package.json $PROJECTPATH/
    - /bin/cp package-lock.json $PROJECTPATH/
    - /bin/cp vite.config.ts $PROJECTPATH/
    - /bin/cp tsconfig.json $PROJECTPATH/
    - /bin/cp tailwind.config.js $PROJECTPATH/
    - /bin/cp -R public/* $DEPLOYPATH/
    - /bin/cp public/.htaccess $DEPLOYPATH/
    - cd $PROJECTPATH
    - composer install --optimize-autoloader --no-dev --no-interaction
    - npm install --production
    - npm run build
    - /bin/cp -R public/build $DEPLOYPATH/
    - cd $DEPLOYPATH
    - rm -f storage
    - ln -s $PROJECTPATH/storage/app/public storage
    - cd $PROJECTPATH
    - chmod -R 775 storage
    - chmod -R 775 bootstrap/cache
    - test -f .env || cp .env.example .env
    - sed -i 's/DB_CONNECTION=msyql/DB_CONNECTION=mysql/g' .env
    - sed -i 's/DB_CONNECTION=msql/DB_CONNECTION=mysql/g' .env
    - grep -q "APP_KEY=" .env || php artisan key:generate --force
    - php artisan migrate --force
    - php artisan db:seed --class=UserSeeder --force
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
