---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - export PROJECTPATH=$HOME/whatsapp-clone
    - mkdir -p $PROJECTPATH
    - /bin/cp -R app $PROJECTPATH/
    - /bin/cp -R bootstrap $PROJECTPATH/
    - /bin/cp -R config $PROJECTPATH/
    - /bin/cp -R database $PROJECTPATH/
    - /bin/cp -R resources $PROJECTPATH/
    - /bin/cp -R routes $PROJECTPATH/
    - /bin/cp -R tests $PROJECTPATH/
    - /bin/cp artisan $PROJECTPATH/
    - /bin/cp composer.json $PROJECTPATH/
    - /bin/cp composer.lock $PROJECTPATH/
    - /bin/cp package.json $PROJECTPATH/
    - /bin/cp package-lock.json $PROJECTPATH/
    - /bin/cp vite.config.ts $PROJECTPATH/
    - /bin/cp tsconfig.json $PROJECTPATH/
    - /bin/cp tailwind.config.js $PROJECTPATH/
    - /bin/cp -R public/* $DEPLOYPATH/
    - /bin/cp public/.htaccess $DEPLOYPATH/
    - cd $PROJECTPATH
    - composer install --optimize-autoloader --no-dev --no-interaction
    - npm install --production
    - npm run build
    - /bin/cp -R public/build $DEPLOYPATH/
    - cd $DEPLOYPATH
    - rm -f storage
    - ln -s $PROJECTPATH/storage/app/public storage
    - cd $PROJECTPATH
    - chmod -R 775 storage
    - chmod -R 775 bootstrap/cache
    - test -f .env || cp .env.example .env
    - sed -i 's/DB_CONNECTION=msyql/DB_CONNECTION=mysql/g' .env
    - sed -i 's/DB_CONNECTION=msql/DB_CONNECTION=mysql/g' .env
    - grep -q "APP_KEY=" .env || php artisan key:generate --force
    - grep -q "^BROADCAST_CONNECTION=" .env || echo "BROADCAST_CONNECTION=reverb" >> .env
    - php -r "if(!file_exists('.env') || !strpos(file_get_contents('.env'), 'REVERB_APP_ID')) { \$id = bin2hex(random_bytes(16)); file_put_contents('.env', \"REVERB_APP_ID=\$id\n\", FILE_APPEND); }"
    - php -r "if(!file_exists('.env') || !strpos(file_get_contents('.env'), 'REVERB_APP_KEY')) { \$key = bin2hex(random_bytes(16)); file_put_contents('.env', \"REVERB_APP_KEY=\$key\nVITE_REVERB_APP_KEY=\$key\n\", FILE_APPEND); }"
    - php -r "if(!file_exists('.env') || !strpos(file_get_contents('.env'), 'REVERB_APP_SECRET')) { \$secret = bin2hex(random_bytes(32)); file_put_contents('.env', \"REVERB_APP_SECRET=\$secret\n\", FILE_APPEND); }"
    - php -r "\$env = file_get_contents('.env'); \$appUrl = preg_match('/APP_URL=(.+)/', \$env, \$m) ? trim(\$m[1], '\"\\'') : ''; \$host = preg_replace('/https?:\\/\\//', '', \$appUrl); \$host = preg_replace('/\\/.*/', '', \$host); \$env = preg_replace('/^REVERB_HOST=.*\\n/m', '', \$env); \$env = preg_replace('/^REVERB_PORT=.*\\n/m', '', \$env); \$env = preg_replace('/^REVERB_SCHEME=.*\\n/m', '', \$env); \$env = preg_replace('/^VITE_REVERB_HOST=.*\\n/m', '', \$env); \$env = preg_replace('/^VITE_REVERB_PORT=.*\\n/m', '', \$env); \$env = preg_replace('/^VITE_REVERB_SCHEME=.*\\n/m', '', \$env); if(\$host) { \$env .= \"REVERB_HOST=\$host\\nREVERB_PORT=443\\nREVERB_SCHEME=https\\nVITE_REVERB_HOST=\$host\\nVITE_REVERB_PORT=443\\nVITE_REVERB_SCHEME=https\\n\"; } file_put_contents('.env', \$env);"
    - php artisan migrate --force
    - php artisan db:seed --class=UserSeeder --force
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
