---
# ЁЯЪА ┘Е┘Д┘Б ╪е╪╣╪п╪з╪п Git Deployment ╪з┘Д╪к┘Д┘В╪з╪ж┘К ┘Д┘А cPanel
# Automatic/Push Deployment - ┘К╪к┘Е ╪з┘Д╪к┘Ж┘Б┘К╪░ ╪к┘Д┘В╪з╪ж┘К╪з┘Л ╪╣┘Ж╪п git push
# ┘З╪░╪з ╪з┘Д┘Е┘Д┘Б ┘К╪м╪и ╪г┘Ж ┘К┘Г┘И┘Ж ┘Б┘К ╪з┘Д╪м╪░╪▒ (root) ┘Д┘Д┘Е╪│╪к┘И╪п╪╣

deployment:
  tasks:
    # ╪к╪н╪п┘К╪п ┘Е╪│╪з╪▒╪з╪к ╪з┘Д┘Е╪м┘Д╪п╪з╪к
    # ┘Б┘К cPanel╪М ╪з┘Д┘Е╪│╪к┘И╪п╪╣ ┘К┘Г┘И┘Ж ╪╣╪з╪п╪й ┘Б┘К ~/repositories/repo-name.git
    # ┘И╪з┘Д┘Е╪м┘Д╪п ╪з┘Д╪н╪з┘Д┘К ┘З┘И working directory ┘Д┘Д┘Е╪│╪к┘И╪п╪╣
    - export DEPLOYPATH=$HOME/public_html
    - export PROJECTPATH=$HOME/whatsapp-clone
    - export REPOPATH=$(pwd)
    
    # ╪е┘Ж╪┤╪з╪б ┘Е╪м┘Д╪п ╪з┘Д┘Е╪┤╪▒┘И╪╣ ╪е╪░╪з ┘Д┘Е ┘К┘Г┘Ж ┘Е┘И╪м┘И╪п╪з┘Л
    - mkdir -p $PROJECTPATH
    
    # ┘Ж╪│╪о ╪м┘Е┘К╪╣ ┘Е┘Д┘Б╪з╪к Laravel ┘Е┘Ж ╪з┘Д┘Е╪│╪к┘И╪п╪╣ ╪е┘Д┘Й ┘Е╪м┘Д╪п ╪з┘Д┘Е╪┤╪▒┘И╪╣
    # тЪая╕П ┘Е┘З┘Е: ┘Д╪з ┘Ж┘Ж╪│╪о ┘Е┘Д┘Б .env (┘К╪н╪к┘И┘К ╪╣┘Д┘Й ┘Е╪╣┘Д┘И┘Е╪з╪к ╪н╪│╪з╪│╪й ┘Д┘Д╪е┘Ж╪к╪з╪м)
    # тЪая╕П ╪з╪│╪к╪л┘Ж╪з╪б: .env, node_modules, vendor, .git, storage (┘Д╪г┘Ж┘З╪з ┘В╪п ╪к╪н╪к┘И┘К ╪╣┘Д┘Й ╪и┘К╪з┘Ж╪з╪к)
    - /bin/cp -R app bootstrap config database resources routes tests $PROJECTPATH/ 2>/dev/null || true
    - /bin/cp artisan composer.json composer.lock package.json package-lock.json $PROJECTPATH/ 2>/dev/null || true
    - /bin/cp vite.config.ts tsconfig.json tailwind.config.js $PROJECTPATH/ 2>/dev/null || true
    # ┘Ж╪│╪о .htaccess ┘Б┘В╪╖ ╪е╪░╪з ┘Д┘Е ┘К┘Г┘Ж ┘Е┘И╪м┘И╪п╪з┘Л (┘Д╪н┘Е╪з┘К╪й ╪з┘Д╪е╪╣╪п╪з╪п╪з╪к ╪з┘Д╪о╪з╪╡╪й ╪╣┘Д┘Й ╪з┘Д╪│┘К╪▒┘Б╪▒)
    - if [ ! -f "$PROJECTPATH/.htaccess" ]; then /bin/cp .htaccess $PROJECTPATH/ 2>/dev/null || true; fi
    # ┘Ж╪│╪о .env.example ┘Г┘Е╪▒╪м╪╣ ┘Б┘В╪╖ (╪е╪░╪з ┘Г╪з┘Ж ┘Е┘И╪м┘И╪п╪з┘Л)
    - /bin/cp .env.example $PROJECTPATH/ 2>/dev/null || true
    
    # ┘Ж╪│╪о ┘Е╪н╪к┘И┘К╪з╪к ┘Е╪м┘Д╪п public ╪е┘Д┘Й public_html
    - /bin/cp -R public/* $DEPLOYPATH/ 2>/dev/null || true
    # ┘Ж╪│╪о public/.htaccess ┘Б┘В╪╖ ╪е╪░╪з ┘Д┘Е ┘К┘Г┘Ж ┘Е┘И╪м┘И╪п╪з┘Л (┘Д╪н┘Е╪з┘К╪й ╪з┘Д╪е╪╣╪п╪з╪п╪з╪к ╪з┘Д╪о╪з╪╡╪й ╪╣┘Д┘Й ╪з┘Д╪│┘К╪▒┘Б╪▒)
    - if [ ! -f "$DEPLOYPATH/.htaccess" ]; then /bin/cp public/.htaccess $DEPLOYPATH/ 2>/dev/null || true; fi
    
    # ╪з┘Д╪з┘Ж╪к┘В╪з┘Д ╪е┘Д┘Й ┘Е╪м┘Д╪п ╪з┘Д┘Е╪┤╪▒┘И╪╣
    - cd $PROJECTPATH
    
    # ╪к╪л╪и┘К╪к ╪к╪и╪╣┘К╪з╪к Composer (╪к╪н╪п┘К╪л ╪е╪░╪з ┘Г╪з┘Ж╪к ┘Е┘И╪м┘И╪п╪й)
    - composer install --optimize-autoloader --no-dev --no-interaction
    
    # ╪к╪л╪и┘К╪к ╪к╪и╪╣┘К╪з╪к npm
    - npm install --production
    
    # ╪и┘Ж╪з╪б ╪з┘Д╪г╪╡┘И┘Д (Assets) ┘Е┘Ж Vite
    - npm run build
    
    # ┘Ж╪│╪о ┘Е╪м┘Д╪п build ┘Е┘Ж public ╪е┘Д┘Й public_html
    - /bin/cp -R public/build $DEPLOYPATH/ 2>/dev/null || true
    
    # ╪е┘Ж╪┤╪з╪б ╪▒╪з╪и╪╖ storage ╪е╪░╪з ┘Д┘Е ┘К┘Г┘Ж ┘Е┘И╪м┘И╪п╪з┘Л
    - if [ ! -L "$DEPLOYPATH/storage" ]; then cd $DEPLOYPATH && rm -rf storage && ln -s $PROJECTPATH/storage/app/public storage; fi
    
    # ╪к╪╣┘К┘К┘Ж ╪з┘Д╪╡┘Д╪з╪н┘К╪з╪к ┘Д┘Д┘Е╪м┘Д╪п╪з╪к ╪з┘Д┘Е┘З┘Е╪й
    - chmod -R 775 storage
    - chmod -R 775 bootstrap/cache
    
    # ╪к╪н╪│┘К┘Ж ╪з┘Д╪г╪п╪з╪б (Cache) - ┘Б┘В╪╖ ╪е╪░╪з ┘Г╪з┘Ж ┘Е┘Д┘Б .env ┘Е┘И╪м┘И╪п
    # тЪая╕П ┘Е┘Д╪з╪н╪╕╪й: ┘Е┘Д┘Б .env ┘К╪м╪и ╪г┘Ж ┘К┘Г┘И┘Ж ┘Е┘И╪м┘И╪п╪з┘Л ╪╣┘Д┘Й ╪з┘Д╪│┘К╪▒┘Б╪▒ ┘В╪и┘Д ╪з┘Д┘Ж╪┤╪▒
    # тЪая╕П ┘Е┘Д┘Б .env ┘Д╪з ┘К┘П╪▒┘Б╪╣ ┘Е┘Ж GitHub ┘Д╪г╪│╪и╪з╪и ╪г┘Е┘Ж┘К╪й
    - if [ -f .env ]; then php artisan config:cache 2>/dev/null || true; fi
    - if [ -f .env ]; then php artisan route:cache 2>/dev/null || true; fi
    - if [ -f .env ]; then php artisan view:cache 2>/dev/null || true; fi
    - if [ -f .env ]; then php artisan event:cache 2>/dev/null || true; fi
    
    # ╪к╪н╪░┘К╪▒ ╪е╪░╪з ┘Д┘Е ┘К┘Г┘Ж ┘Е┘Д┘Б .env ┘Е┘И╪м┘И╪п╪з┘Л
    - if [ ! -f .env ]; then echo "тЪая╕П  ╪к╪н╪░┘К╪▒: ┘Е┘Д┘Б .env ╪║┘К╪▒ ┘Е┘И╪м┘И╪п! ┘К╪▒╪м┘Й ╪е┘Ж╪┤╪з╪д┘З ┘К╪п┘И┘К╪з┘Л ╪╣┘Д┘Й ╪з┘Д╪│┘К╪▒┘Б╪▒."; fi
    
    # ┘Е┘Д╪з╪н╪╕╪з╪к ┘Е┘З┘Е╪й:
    # тЪая╕П ┘Е┘Д┘Б .env ┘Д╪з ┘К┘П┘Ж╪│╪о ┘Е┘Ж GitHub (┘К╪н╪к┘И┘К ╪╣┘Д┘Й ┘Е╪╣┘Д┘И┘Е╪з╪к ╪н╪│╪з╪│╪й)
    # тЪая╕П ┘Е┘Д┘Б .htaccess ┘Д╪з ┘К┘П╪│╪к╪и╪п┘Д ╪е╪░╪з ┘Г╪з┘Ж ┘Е┘И╪м┘И╪п╪з┘Л ╪╣┘Д┘Й ╪з┘Д╪│┘К╪▒┘Б╪▒ (┘Д╪н┘Е╪з┘К╪й ╪з┘Д╪е╪╣╪п╪з╪п╪з╪к ╪з┘Д╪о╪з╪╡╪й)
    # тЬЕ ┘К┘Е┘Г┘Ж┘Г ╪к╪╣╪п┘К┘Д .env ┘И .htaccess ┘К╪п┘И┘К╪з┘Л ╪╣┘Д┘Й ╪з┘Д╪│┘К╪▒┘Б╪▒ ╪п┘И┘Ж ╪з┘Д┘В┘Д┘В ┘Е┘Ж ╪з╪│╪к╪и╪п╪з┘Д┘З╪з

